### ISSUE TITLE
regression error

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry-console#236]
`scripts/translations.js` used to generate a translation file with parsed markdown.
The file has since been changed to include a watch and throws errors when trying to run it.

**Comment by luckyluck** [comment]
@MortenHofft , unfortunately, I can't reproduce the bug. Also, I changed a bit the way how to launch this command starting the project. Would you mind to add your log with errors or, perhaps, clarify the case how to launch the command with error?

**Comment by MortenHofft** [comment]
just pulled the newest enhancement branch. Running `npm run build:locale` which is a defined script in the package will throw.

```

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../locales/locales/da.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at FSWatcher.updateFile (/Users/hoefft/dev/git/gbif/registry-console/scripts/translations.js:30:32)
    at FSWatcher.emit (events.js:189:13)
    at FSWatcher.<anonymous> (/Users/hoefft/dev/git/gbif/registry-console/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/Users/hoefft/dev/git/gbif/registry-console/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/Users/hoefft/dev/git/gbif/registry-console/node_modules/chokidar/lib/fsevents-handler.js:329:12)
    at FSWatcher.<anonymous> (/Users/hoefft/dev/git/gbif/registry-console/node_modules/chokidar/lib/fsevents-handler.js:372:11)
    at ReaddirpReadable.emit (events.js:189:13)
    at addChunk (/Users/hoefft/dev/git/gbif/registry-console/node_modules/readable-stream/lib/_stream_readable.js:291:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gbif-admin-starter@0.1.0 build:locale: `node scripts/translations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gbif-admin-starter@0.1.0 build:locale script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hoefft/.npm/_logs/2019-02-22T10_13_30_122Z-debug.log
mhofft:registry-console hoefft$ npm run build:locale
```

**Comment by MortenHofft** [comment]
Same goes when running `npm run start:dev`

**Comment by luckyluck** [comment]
I fixed the bug with the file path and added `build:locale` to the main build command (it was so initially and, perhaps, there is such a need, because localization can be edited separately).
